import SwiftUI

public enum GrowColorScheme {
    case textNormal
    case textDarken
    case textAlt
    case textInverse
    case textDisabled
    case textWarning
    case buttonPrimary
    case buttonPrimaryPressed
    case buttonPrimaryDisabled
    case buttonText
    case buttonTextDisabled
    case tabButtonPrimary
    case radioButtonPrimary
    case radioButtonPrimaryDisabled
    case radioButtonSecondary
    case radioButtonSecondaryDisabled
    case background
    case backgroundAlt
    case backgroundInverse
    case github
    case baekjoon
    case dividerNormal
    case textFieldIcon
    case textFieldIconDisabled
    case textFieldPrimary
    case textFieldSecondary
    case textFieldSecondaryDisabled
    case textFieldTextDisabled
    case avatarLabel
    case avatarBackground
    case elevationBlack1
    case elevationBlack2
    case elevationBlack3
    case bottomTabPrimary
    case bottomTabPrimaryDisabled
    case bottomTabSecondary
    case likePrimary
    case likePrimaryDisabled
    case likeSecondary
    case likeSecondaryDisabled
}
